### ISSUE TITLE
[`Proposal`] Css repository

### ISSUE THREAD

**Issue by Benliam12** [NatickYT/KoolKidMods#1]
There are no Css repository to enter your css rules. You are repeating the same styles over and over on your different pages. 
For the futur of the developpment of your project, it is crutial that you organise your files correctly. 

By the css that is recurrent, I'm talking about this one:

```css
        body {
          background-color: white;
      }
        /* Header 1 */
        h1 {
          color: black;
          text-align: center;
      }
        /* Paragraphs */
        p {
          font-family: verdana;
          font-size: 20px;
          color: black;
      }
        /* Unvisited Links */
        a:link {
          color: black;
      }
        /* Visited Links */
        a:visited {
          color: black;
      }
        /* Mice On Links */
        a:hover {
          color: black;
      }
        /* Selected Links */
        a:active {
          color: black;
      }
```
